function uj(a){for(var b=Mc;;)if(H(a))b=Oc.a(b,E(a)),a=H(a);else return D(b)}function vj(a,b,c,d){return M(new T(null,2,5,V,[d,null],null),new ra(null,3,[new s("zip","make-node","zip/make-node",1103800591),c,new s("zip","children","zip/children",-940194589),b,new s("zip","branch?","zip/branch?",-998880862),a],null))}function wj(a){return a.b?a.b(0):a.call(null,0)}function xj(a){return(new s("zip","branch?","zip/branch?",-998880862)).b(Vc(a)).call(null,wj(a))}
function yj(a){if(u(xj(a)))return(new s("zip","children","zip/children",-940194589)).b(Vc(a)).call(null,wj(a));throw"called children on a leaf node";}function zj(a,b,c){return(new s("zip","make-node","zip/make-node",1103800591)).b(Vc(a)).call(null,b,c)}
function Aj(a){if(u(xj(a))){var b=O.c(a,0,null),c=O.c(a,1,null),d=yj(a),e=O.c(d,0,null),f=Jd(d);return u(d)?M(new T(null,2,5,V,[e,new ra(null,4,[new s(null,"l","l",1395893423),Mc,new s(null,"pnodes","pnodes",1739080565),u(c)?Oc.a((new s(null,"pnodes","pnodes",1739080565)).b(c),b):new T(null,1,5,V,[b],null),new s(null,"ppath","ppath",-1758182784),c,new s(null,"r","r",-471384190),f],null)],null),Vc(a)):null}return null}
function Bj(a){var b=O.c(a,0,null),c=O.c(a,1,null),d=md(c)?S.a(Ne,c):c,c=Q.a(d,new s(null,"l","l",1395893423)),e=Q.a(d,new s(null,"ppath","ppath",-1758182784)),f=Q.a(d,new s(null,"pnodes","pnodes",1739080565)),g=Q.a(d,new s(null,"r","r",-471384190)),d=Q.a(d,new s(null,"changed?","changed?",-437828330));return u(f)?(f=Wc(f),M(u(d)?new T(null,2,5,V,[zj(a,f,ge.a(c,L(b,g))),u(e)?R.c(e,new s(null,"changed?","changed?",-437828330),!0):e],null):new T(null,2,5,V,[f,e],null),Vc(a))):null}
function Cj(a){var b=O.c(a,0,null),c=O.c(a,1,null),c=md(c)?S.a(Ne,c):c,d=Q.a(c,new s(null,"l","l",1395893423)),e=Q.a(c,new s(null,"r","r",-471384190)),f=O.c(e,0,null),g=Jd(e);return u(u(c)?e:c)?M(new T(null,2,5,V,[f,R.d(c,new s(null,"l","l",1395893423),Oc.a(d,b),I([new s(null,"r","r",-471384190),g],0))],null),Vc(a)):null}
function Dj(a){var b=O.c(a,0,null),c=O.c(a,1,null),c=md(c)?S.a(Ne,c):c,d=Q.a(c,new s(null,"l","l",1395893423)),e=Q.a(c,new s(null,"r","r",-471384190));return u(u(c)?e:c)?M(new T(null,2,5,V,[Lc(e),R.d(c,new s(null,"l","l",1395893423),S.m(Oc,d,b,uj(e)),I([new s(null,"r","r",-471384190),null],0))],null),Vc(a)):a}
function Ej(a){var b=O.c(a,0,null),c=O.c(a,1,null),c=md(c)?S.a(Ne,c):c,d=Q.a(c,new s(null,"l","l",1395893423)),e=Q.a(c,new s(null,"r","r",-471384190));return u(u(c)?D(d):c)?M(new T(null,2,5,V,[Wc(d),R.d(c,new s(null,"l","l",1395893423),Xc(d),I([new s(null,"r","r",-471384190),L(b,e)],0))],null),Vc(a)):null}function Fj(a,b){O.c(a,0,null);var c=O.c(a,1,null);return M(new T(null,2,5,V,[b,R.c(c,new s(null,"changed?","changed?",-437828330),!0)],null),Vc(a))}
var Gj=function(){function a(a,d,e){var f=null;2<arguments.length&&(f=I(Array.prototype.slice.call(arguments,2),0));return b.call(this,a,d,f)}function b(a,b,e){return Fj(a,S.c(b,wj(a),e))}a.j=2;a.f=function(a){var d=E(a);a=H(a);var e=E(a);a=F(a);return b(d,e,a)};a.d=b;return a}();q("mori.zip.zipper",vj);q("mori.zip.seq_zip",function(a){return vj(md,yd,function(a,c){return M(c,Vc(a))},a)});q("mori.zip.vector_zip",function(a){return vj(gd,D,function(a,c){return M(Lf(c),Vc(a))},a)});q("mori.zip.node",wj);q("mori.zip.is_branch",xj);q("mori.zip.children",yj);q("mori.zip.make_node",zj);q("mori.zip.path",function(a){return(new s(null,"pnodes","pnodes",1739080565)).b(a.b?a.b(1):a.call(null,1))});
q("mori.zip.lefts",function(a){return D((new s(null,"l","l",1395893423)).b(a.b?a.b(1):a.call(null,1)))});q("mori.zip.rights",function(a){return(new s(null,"r","r",-471384190)).b(a.b?a.b(1):a.call(null,1))});q("mori.zip.down",Aj);q("mori.zip.up",Bj);q("mori.zip.root",function(a){for(;;){if(rc.a(new s(null,"end","end",-268185958),a.b?a.b(1):a.call(null,1)))return wj(a);var b=Bj(a);if(u(b))a=b;else return wj(a)}});q("mori.zip.right",Cj);q("mori.zip.rightmost",Dj);q("mori.zip.left",Ej);
q("mori.zip.leftmost",function(a){var b=O.c(a,0,null),c=O.c(a,1,null),c=md(c)?S.a(Ne,c):c,d=Q.a(c,new s(null,"l","l",1395893423)),e=Q.a(c,new s(null,"r","r",-471384190));return u(u(c)?D(d):c)?M(new T(null,2,5,V,[E(d),R.d(c,new s(null,"l","l",1395893423),Mc,I([new s(null,"r","r",-471384190),ge.d(F(d),new T(null,1,5,V,[b],null),I([e],0))],0))],null),Vc(a)):a});
q("mori.zip.insert_left",function(a,b){var c=O.c(a,0,null),d=O.c(a,1,null),d=md(d)?S.a(Ne,d):d,e=Q.a(d,new s(null,"l","l",1395893423));if(null==d)throw"Insert at top";return M(new T(null,2,5,V,[c,R.d(d,new s(null,"l","l",1395893423),Oc.a(e,b),I([new s(null,"changed?","changed?",-437828330),!0],0))],null),Vc(a))});
q("mori.zip.insert_right",function(a,b){var c=O.c(a,0,null),d=O.c(a,1,null),d=md(d)?S.a(Ne,d):d,e=Q.a(d,new s(null,"r","r",-471384190));if(null==d)throw"Insert at top";return M(new T(null,2,5,V,[c,R.d(d,new s(null,"r","r",-471384190),L(b,e),I([new s(null,"changed?","changed?",-437828330),!0],0))],null),Vc(a))});q("mori.zip.replace",Fj);q("mori.zip.edit",Gj);q("mori.zip.insert_child",function(a,b){return Fj(a,zj(a,wj(a),L(b,yj(a))))});
q("mori.zip.append_child",function(a,b){return Fj(a,zj(a,wj(a),ge.a(yj(a),new T(null,1,5,V,[b],null))))});q("mori.zip.next",function(a){if(rc.a(new s(null,"end","end",-268185958),a.b?a.b(1):a.call(null,1)))return a;var b;b=xj(a);b=u(b)?Aj(a):b;if(u(b))return b;b=Cj(a);if(u(b))return b;for(;;)if(u(Bj(a))){b=Cj(Bj(a));if(u(b))return b;a=Bj(a)}else return new T(null,2,5,V,[wj(a),new s(null,"end","end",-268185958)],null)});
q("mori.zip.prev",function(a){var b=Ej(a);if(u(b))for(a=b;;)if(b=xj(a),b=u(b)?Aj(a):b,u(b))a=Dj(b);else return a;else return Bj(a)});q("mori.zip.is_end",function(a){return rc.a(new s(null,"end","end",-268185958),a.b?a.b(1):a.call(null,1))});
q("mori.zip.remove",function(a){O.c(a,0,null);var b=O.c(a,1,null),b=md(b)?S.a(Ne,b):b,c=Q.a(b,new s(null,"l","l",1395893423)),d=Q.a(b,new s(null,"ppath","ppath",-1758182784)),e=Q.a(b,new s(null,"pnodes","pnodes",1739080565)),f=Q.a(b,new s(null,"r","r",-471384190));if(null==b)throw"Remove at top";if(0<N(c))for(a=M(new T(null,2,5,V,[Wc(c),R.d(b,new s(null,"l","l",1395893423),Xc(c),I([new s(null,"changed?","changed?",-437828330),!0],0))],null),Vc(a));;)if(b=xj(a),b=u(b)?Aj(a):b,u(b))a=Dj(b);else return a;
else return M(new T(null,2,5,V,[zj(a,Wc(e),f),u(d)?R.c(d,new s(null,"changed?","changed?",-437828330),!0):d],null),Vc(a))});
//# sourceMappingURL=src/mori.zip.js.map
